- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_packages:
      - { name: ansible }
      - { name: git }
      - { name: jq }
      - { name: mas }
      - { name: nkf }
      - { name: node }
      - { name: yarn }
      - { name: watchman }
      - { name: openssl }
      - { name: python }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: tmux }
      - { name: tree }
      - { name: wget }
      - { name: haskell-stack }
      - { name: awscli }
      - { name: postgresql}
      - { name: wireshark}
      - { name: go}
      - { name: packer}
      - { name: carthage}
      - { name: kylef/formulae/swiftenv }
      - { name: pwgen }

    homebrew_cask_packages:
      - appcleaner
      - astah-community
      - vivaldi
      - firefox
      - google-chrome
      - google-drive
      - java
      - android-studio
      - vagrant
      - virtualbox
      - google-japanese-ime
      - visual-studio-code
      - evernote
      - iterm2
      - the-unarchiver
      - google-cloud-sdk

    mas_packages:
      - { name: Xcode, id: 497799835 }

  tasks:
    # brew update
    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - brew

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: "{{ homebrew_packages }}"
      tags:
        - brew

    # brew cask install
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item }}" state=present
      with_items: "{{ homebrew_cask_packages }}"
      ignore_errors: true
      tags:
        - cask

    # mas install
    - name: install mas (App Store) packages
      shell: mas install "{{ item.id }}"
      with_items: "{{ mas_packages }}"
      register: ret
      changed_when: '"already installed" not in ret.stdout'
      tags:
        - mas

    # mas upgrade
    - name: upgrade all mas (App Store) packages
      shell: mas upgrade
      register: ret
      changed_when: '"Everything is up-to-date" not in ret.stdout'
      tags:
        - mas
