- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    homebrew_packages:
      - { name: git }
      - { name: jq }
      - { name: asdf }
      - { name: openssl }
      - { name: tmux }
      - { name: tree }
      - { name: wget }
      - { name: wireshark}

    homebrew_cask_packages:
      - vivaldi
      - google-chrome
      - google-japanese-ime
      - visual-studio-code
      - evernote
      - slack

  tasks:
    # brew update
    - name: update homebrew
      homebrew: update_homebrew=yes
      tags:
        - brew

    # brew instal
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: "{{ homebrew_packages }}"
      tags:
        - brew

    # brew cask install
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item }}" state=present
      with_items: "{{ homebrew_cask_packages }}"
      ignore_errors: true
      tags:
        - cask

