- name: Install packages to build git
  become: yes
  yum:
    state: present
    name:
      - curl-devel
      - expat-devel
      - perl-ExtUtils-MakeMaker
- name: Check if git is installed
  stat: path={{ bin_dir }}/git
  register: git
- name: Check the version of installed git
  command: "{{ bin_dir }}/git --version warn=false"
  register: git_version
  changed_when: false
  when: git.stat.exists == true
- name: Make a directory to download git
  become: yes
  file: path={{ src_dir }} state=directory owner=root group=root mode=755
  when: (git.stat.exists == false) or
        (git.stat.exists == true and git_version.stdout != "git version" + version)
- name: download git version {{ version }}
  become: yes
  unarchive:
    src: https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz
    dest: "{{ src_dir }}"
    copy: no
  when: (git.stat.exists == false) or
        (git.stat.exists == true and git_version.stdout != "git version" + version)
- name: make all
  become: yes
  make:
    chdir: "{{ src_dir }}/git-{{ version }}"
    target: all
    params:
      prefix: "{{ prefix_dir }}"
  when: (git.stat.exists == false) or
        (git.stat.exists == true and git_version.stdout != "git version" + version)
- name: make install
  become: yes
  make:
    chdir: "{{ src_dir }}/git-{{ version }}"
    target: install
    params:
      prefix: "{{ prefix_dir }}"
  when: (git.stat.exists == false) or
        (git.stat.exists == true and git_version.stdout != "git version" + version)
